name: GitHub Page Deploy
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        persist-credentials: false

    - name: Generate Allure report
      uses: simple-elf/allure-report-action@v1.5
      if: always()
      with:
        allure_results: allure-results
        allure_report: allure-report
        allure_history: allure-history
        #gh_pages: gh-pages
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history

    - name: Post the link to the report
      if: always()
      uses: Sibz/github-status-action@v1
      with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Allure report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha || github.sha}}
          target_url: https://nikithapreethamsonos.github.io/gitactions_test/${{ github.run_number }}
          
          
