name: GitHub Page Deploy
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        persist-credentials: false

    - name: Generate Allure report
      uses: simple-elf/allure-report-action@v1.5
      if: always()
      with:
        allure_results: allure-results
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
    
    - name: Post Comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        number:  ${{ github.event.head_commit.message }}
        owner: Sonos-Inc
        repo: pdsw-sonos-controller-player-s2
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          Allure Report: 
          https://nikithapreethamsonos.github.io/gitactions_test/${{ github.run_number }}
