name: GitHub Page Deploy
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Generate Allure report
      uses: simple-elf/allure-report-action@v1.5
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20
          
    - name: Publish Allure report
      uses: JamesIves/github-pages-deploy-action@v4
      with: 
        folder: allure-results
