# This is a basic workflow to help you get started with Actions
name: learn-github-actions
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: First interaction
        uses: actions/first-interaction@v1.1.0
        with:
      # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
          repo-token: secrets.GITHUB_TOKEN 
      # Comment to post on an individual's first issue
          issue-message: first issue message
      # Comment to post on an individual's first pull request
          pr-message: first pull request message
